[package]
name = "konomanoasa-tree-sitter-yaml"
version = "0.1.0"
edition = "2024"
description = "Tree-sitter grammar for YAML."
readme = "README.md"
repository = "https://github.com/konomanoasa/tree-sitter-yaml"
license = "MIT"
build = "bindings/rust/build.rs"
links = "tree-sitter-yaml"
include = [
  "/LICENSE",
  "/README.md",
  "/bindings/rust/*.rs",
  "/queries/*.scm",
  "/src/*.c",
  "/src/node-types.json",
  "/src/tree_sitter/*.h",
  "/test/bindings.test.rs",
]

[lib]
path = "bindings/rust/lib.rs"

[[test]]
name = "bindings"
path = "test/bindings.test.rs"

[dependencies]
tree-sitter-language = "0.1.8"

[dev-dependencies]
tree-sitter = "0.27.0"

[build-dependencies]
cc = "1.4"
